matrix:
  include:

# build and test backend
    - language: java
      sudo: required
      jdk: oraclejdk8
      before_script:
        - cd code/backend
      script:
        - sudo chmod +x mvnw
        - ./mvnw test
        - ./mvnw install

# build and test frontend web
    - language: node_js
      sudo: required
      node_js:
      - "node"
      - "8"
      before_script:
        - cd code/frontend/web
      script:
        - npm install
        - npm test
        - npm run build

# build and test frontend mobile
    - language: node_js
      sudo: required
      node_js:
        - "node"
        - "8"
      before_script:
        - cd code/frontend/mobile
      script:
        - npm install
        - npm test

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - node_modules

notifications:
  email:
    - florian.widder@live.de
