matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd code/frontend
      script:
        - dir
        - ./mvnw test
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    - language: node_js
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 8.9.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      before_script:
        - cd frontend
      script:
        - cd web
        - yarn install
        - yarn test
        - yarn build
        - cd ../mobile
        - yarn install
        - yarn test

cache:
  yarn: true

notifications:
  email:
    - florian.widder@live.de
