matrix:
  include:
    - language: java
      sudo: required
      jdk: oraclejdk8
      before_script:
        - cd code/backend
      script:
        - dir
        - sudo chmod 777 mvnw
        - ./mvnw test
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

    - language: node_js
      sudo: required
      node_js:
      - "node"
      - "8"
      before_script:
        - cd frontend
      script:
        - cd web
        - node install
        - node test
        - node build
        - cd ../mobile
        - node install
        - node test

cache:
  yarn: true

notifications:
  email:
    - florian.widder@live.de
