matrix:
  include:
    - language: java
      sudo: required
      jdk: oraclejdk8
      before_script:
        - cd code/backend
      script:
        - sudo chmod 777 mvnw
        - ./mvnw test
        - ./mvnw install

    - language: node_js
      sudo: required
      node_js:
      - "node"
      - "8"
      before_script:
        - cd code/frontend/web
      script:
        - npm install
        - npm test
        - npm run build

    - language: android
      sudo: required
      before_script:
        - cd code/frontend/mobile
      before_install:
        - nvm install 6
        - node --version
      install:
        -  npm install
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleRelease

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - code/frontend/mobile/node_modules
  - code/frontend/web/node_modules
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

notifications:
  email:
    - florian.widder@live.de
